### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by ucitx** [Holmose/yngbwscript#2]
2023-11-14 17:00:14.247 | ERROR    | AiBot._WebBase:__send_data:107 - send/read tcp data error: 'CustomWebScript' object has no attribute '_lock'
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 4485)
Traceback (most recent call last):
  File "d:\Program Files\python\Lib\socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "d:\Program Files\python\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "d:\Program Files\python\Lib\site-packages\AiBot\WebBot.py", line 20, in __init__
    super().__init__(request, client_address, server)
  File "d:\Program Files\python\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "d:\Program Files\python\Lib\site-packages\AiBot\WebBot.py", line 25, in handle
    self.script_main()
  File "d:\Program Files\python\web_bot.py", line 53, in script_main
    self.goto("https://www.ynsgbzx.cn/index.aspx")
  File "d:\Program Files\python\Lib\site-packages\AiBot\_WebBase.py", line 120, in goto
    return self.__send_data("goto", url) == "true"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Program Files\python\Lib\site-packages\AiBot\_WebBase.py", line 108, in __send_data
    raise e
  File "d:\Program Files\python\Lib\site-packages\AiBot\_WebBase.py", line 94, in __send_data
    with self._lock:
         ^^^^^^^^^^
AttributeError: 'CustomWebScript' object has no attribute '_lock'
----------------------------------------

**Comment by Holmose** [comment]
可以的话 请截图

**Comment by ucitx** [comment]
只打开了浏览器，没有打开干部在线网站

**Comment by ucitx** [comment]
只打开了浏览器，没有打开干部在线网站

**Comment by ucitx** [comment]
![py](https://github.com/Holmose/yngbwscript/assets/63827852/cb3e30a1-9554-43fa-bf0e-313245a3b297)
如图示

**Comment by Holmose** [comment]
打开了说明环境没有问题了，第一次运行会打不开网站，多运行几次就可以了，同时浏览器必须全部关闭，不然 aibot 程序会找不到调用那个浏览器

**Comment by ucitx** [comment]
可以运行了，我试了一下，问题应该是我的python的组件版本和运行环境不一样
